#!/bin/bash

echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                 🚀 SHEDOW AI - QUICK START 🚀                 ║"
echo "║         Complete AI Voice Assistant - Ready to Deploy         ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 What You Have:"
echo "  ✅ Complete Android App (Kotlin)"
echo "  ✅ Production Backend (Node.js + Docker)"
echo "  ✅ Build Scripts (One-click deploy)"
echo "  ✅ Play Store Kit (Ready to publish)"
echo "  ✅ Full Documentation (Setup guides)"
echo ""

echo "🎯 Quick Start Options:"
echo ""
echo "  [1] Test Android App (30 min)"
echo "      - Open in Android Studio"
echo "      - Click Run on emulator"
echo "      - Say 'Hey SHEDOW'"
echo ""
echo "  [2] Deploy Backend Locally (1 hour)"
echo "      - npm install && npm start"
echo "      - Backend runs on :3000"
echo ""
echo "  [3] Build APK for Phone (30 min)"
echo "      - bash deploy/build-apk.sh"
echo "      - Install on device"
echo ""
echo "  [4] Launch on Play Store (2 hours)"
echo "      - bash deploy/build-aab.sh"
echo "      - Upload to Play Store"
echo "      - Live in 24-48 hours"
echo ""
echo "  [5] Full Production Deploy (3 hours)"
echo "      - Deploy backend (Docker/Cloud)"
echo "      - Build release APK"
echo "      - Submit to Play Store"
echo ""

echo "📚 Documentation:"
echo "  📖 GETTING_STARTED.md  - Start here!"
echo "  📖 COMPLETE_SETUP_GUIDE.md - Full instructions"
echo "  📖 docs/architecture.md - Technical details"
echo ""

echo "🔑 You'll Need:"
echo "  1. OpenAI API Key: https://platform.openai.com/api-keys"
echo "  2. Porcupine Key: https://console.picovoice.ai/"
echo "  3. Google Play Account: https://play.google.com/console/"
echo ""

echo "🚀 First Step:"
echo "  Read: GETTING_STARTED.md"
echo "  Run:  bash deploy/build-apk.sh"
echo ""

echo "💚 Good luck! You've got this!"
echo ""
echo "Questions? Check COMPLETE_SETUP_GUIDE.md"
echo ""
