#!/bin/bash

echo "🚀 SHEDOW AI - Complete Setup Guide"
echo ""
echo "Step 1: Prerequisites"
echo "  - Android Studio 2023.1+"
echo "  - Node.js 18+"
echo "  - Java 11+"
echo "  - Gradle 8.0+"
echo ""
echo "Step 2: Get API Keys"
echo "  - OpenAI: https://platform.openai.com/api-keys"
echo "  - Porcupine: https://console.picovoice.ai/"
echo ""
echo "Step 3: Update Configuration"
echo "  - Add OPENAI_API_KEY to backend/.env"
echo "  - Add Porcupine key to WakeWordService.kt"
echo ""
echo "Step 4: Build Backend"
echo "  cd backend"
echo "  npm install"
echo "  OPENAI_API_KEY=sk-xxx npm start"
echo ""
echo "Step 5: Build Android App"
echo "  cd android"
echo "  ./gradlew build"
echo ""
echo "Step 6: Test on Device"
echo "  adb install -r app/build/outputs/apk/debug/app-debug.apk"
echo ""
echo "Step 7: Deploy to Play Store"
echo "  bash deploy/build-aab.sh"
echo "  bash deploy/sign-apk.sh"
echo "  Upload to Google Play Console"
echo ""
echo "✅ Setup complete!"
